package Util;

public enum Routes {
     ADMIN_DASHBOARD, ADMIN_LOGIN, ADMIN_REGISTER, COMPUTER_MANAGE, CUSTOMER_MANAGE, HARDWARE_MANAGE, HOME_PAGE, LAPTOP_MANAGE, LOGIN, REPAIR_MANAGE, SUPPLIER_MANAGE, USER_DASHBOARD, USER_LOGIN, USER_REGISTER

}
